# Generated by Django 3.1.6 on 2021-02-16 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Create')),
                ('modified', models.DateField(auto_now=True, verbose_name='Update')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('service', models.CharField(max_length=100, verbose_name='Service')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('icon', models.CharField(choices=[('lni-vector', 'Vector'), ('lni-pallet', 'Pallet'), ('lni-stats-up', 'Graphic'), ('lni-code-alt', 'Code'), ('lni-lock', 'Lock'), ('lni-code', 'HTML')], max_length=12, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Create')),
                ('modified', models.DateField(auto_now=True, verbose_name='Update')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('pricing', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pricing')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('link', models.CharField(default='#', max_length=100, verbose_name='Link')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.feature', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Pricing',
            },
        ),
    ]
