# Generated by Django 3.1.6 on 2021-02-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'verbose_name': 'Feature', 'verbose_name_plural': 'Features'},
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='pricing',
        ),
        migrations.AddField(
            model_name='pricing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
