# Generated by Django 3.1.6 on 2021-02-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210216_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='icon',
            new_name='icone',
        ),
    ]
