# Generated by Django 3.1.6 on 2021-02-16 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210216_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='icone',
            new_name='icon',
        ),
    ]
